/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "ltweb5"
version = "0.0.1-SNAPSHOT"
description = "ltweb5"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}


dependencies {
	implementation("org.springframework:spring-webmvc:5.3.39")
	implementation("javax.servlet:jstl:1.2")
	compileOnly("javax.servlet:javax.servlet-api:4.0.1")
	
}

copy {
	from(configurations.runtimeClasspath)
	into("src/main/webapp/WEB-INF/lib")
}